<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.12" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
    <Resource Include="app.png" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="DriveTester.Tests\**" />
    <EmbeddedResource Remove="DriveTester.Tests\**" />
    <None Remove="DriveTester.Tests\**" />
    <Page Remove="DriveTester.Tests\**" />
  </ItemGroup>

</Project>
